apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provision-dashboard
data:
{{ (.Files.Glob "config/provisioning/dashboard.yaml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provision-datasource
data:
{{ (.Files.Glob "config/provisioning/datasource.yaml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  GF_USERS_DISABLE_LOGIN_FORM: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
  GF_AUTH_ANONYMOUS_HIDE_VERSION: "true"
  GF_PUBLIC_DASHBOARDS_ENABLED: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
{{ (.Files.Glob "dashboards/*").AsConfig | indent 2 }}
