{
 "title": "Object Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_activeCount,instance)"
    }
   },
   {
    "name": "object_name",
    "label": "Object Name",
    "query": {
     "query": "label_values({prefix=\"map\"},object_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hits Per Second",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(object_name) (rate(com_hazelcast_Metrics_hits{object_name=~\"$object_name\", instance=~\"$Instance\"}[5m]))",
     "legendFormat": "{{object_name}}"
    }
   ]
  },
  {
   "title": "Hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(object_name) (com_hazelcast_Metrics_hits{instance=~\"$Instance\", object_name=~\"$object_name\"})",
     "legendFormat": "{{object_name}}"
    }
   ]
  },
  {
   "title": "Query Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(object_name) (com_hazelcast_Metrics_queryCount{instance=~\"$Instance\", object_name=~\"$object_name\"})",
     "legendFormat": "{{object_name}}"
    }
   ]
  },
  {
   "title": "Put Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(object_name) (com_hazelcast_Metrics_putCount{instance=~\"$Instance\", object_name=~\"$object_name\"})",
     "legendFormat": "{{object_name}}"
    }
   ]
  },
  {
   "title": "Delete Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sum by(object_name) (com_hazelcast_Metrics_removeCount{instance=~\"$Instance\", object_name=~\"$object_name\"})",
     "legendFormat": "{{object_name}}"
    }
   ]
  }
 ]
}