apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  sessionAffinity: None
  type: ClusterIP